#!/usr/bin/env python3
"""Summarize real perfdiag JSON/CSV output; does not run or invent measurements."""
import argparse
import csv
import json
import math
from pathlib import Path
import statistics

p=argparse.ArgumentParser()
p.add_argument('--raw',required=True,type=Path)
p.add_argument('--out',required=True,type=Path)
a=p.parse_args(); raw=a.raw.resolve(); out=a.out.resolve(); out.mkdir(parents=True,exist_ok=True)

def load(name): return json.loads((raw/(name+'.json')).read_text())
def median(rows,k): return statistics.median(r[k] for r in rows)
bench=load('BENCH_RESULTS'); http=load('HTTP_SUMMARIES'); io=load('IO_SUMMARIES'); samples=load('PROCESS_SAMPLES'); requests=load('HTTP_REQUESTS'); persists=load('PERSIST_SAMPLES'); commands=load('commands'); meta=load('RUN_METADATA')
mainh=[r for r in http if r['run']=='http-matrix-3']; mainio=[r for r in io if r['run']=='http-matrix-3']
expected_scenarios=len(meta['history_counts'])*len(meta['client_counts'])*3
expected_requests=sum(meta['client_counts'])*meta['polls_per_client']*len(meta['history_counts'])*3
assert len(mainh)==len(mainio)==expected_scenarios
assert sum(r['requests'] for r in mainh)==sum(r['persist_calls'] for r in mainio)==expected_requests
assert len([r for r in requests if r['run']=='http-matrix-3'])==expected_requests
assert len([r for r in persists if r['run']=='http-matrix-3'])==expected_requests
assert all(r['failures']==0 for r in mainh)
bsummary=[]
for run in ['gateway-bench-3','event-only-bench-3']:
 for name in sorted({r['benchmark'] for r in bench if r['run']==run}):
  rs=[r for r in bench if r['run']==run and r['benchmark']==name]
  assert len(rs)==3
  bsummary.append({'run':run,'benchmark':name,'repeats':len(rs),'ns_per_op_median':median(rs,'ns_per_op'),'ns_per_op_min':min(r['ns_per_op'] for r in rs),'ns_per_op_max':max(r['ns_per_op'] for r in rs),'bytes_per_op_median':median(rs,'bytes_per_op'),'allocs_per_op_median':median(rs,'allocs_per_op')})
hsummary=[]
for key in sorted({(r['history'],r['clients']) for r in mainh}):
 rs=[r for r in mainh if (r['history'],r['clients'])==key]; ios=[r for r in mainio if (r['history'],r['clients'])==key]; assert len(rs)==len(ios)==3
 hsummary.append({'history':key[0],'clients':key[1],'sessions':key[1],'active_endpoints':key[1],'repeats':3,'requests':sum(r['requests'] for r in rs),'p95_ms_median':median(rs,'p95_ms'),'p99_ms_median':median(rs,'p99_ms'),'p95_ms_min':min(r['p95_ms'] for r in rs),'p95_ms_max':max(r['p95_ms'] for r in rs),'requests_per_s_median':median(rs,'rate_requests_per_second'),'alloc_bytes_per_request_median':statistics.median(r['totalalloc_delta_bytes']/r['requests'] for r in rs),'snapshot_bytes_per_persist_median':median(ios,'bytes_per_persist'),'write_bytes_per_persist_median':statistics.median(r['write_bytes_delta']/r['persist_calls'] for r in ios),'wchar_bytes_per_persist_median':statistics.median(r['wchar_delta']/r['persist_calls'] for r in ios),'write_bytes_per_s_median':median(ios,'write_bytes_per_second'),'emitted_to_netgrowth_median':median(ios,'emitted_to_net_file_growth_ratio'),'net_file_growth_bytes_median':median(ios,'net_file_growth_bytes'),'persists_per_request_median':median(ios,'persist_per_request'),'gc_count_median':median(rs,'numgc_delta'),'gc_pause_total_ns_median':median(rs,'pause_delta_ns'),'handler_budget_status':'FAIL' if median(rs,'p95_ms')>200 or median(rs,'p99_ms')>500 else 'WITHIN_SMALL_SAMPLE_ONLY'})
psummary=[]
for label in ['gateway-bench-3','event-only-bench-3','http-matrix-3','profile-SaveSnapshot','profile-LoadSnapshot','profile-http']:
 rs=[r for r in samples if r['command']==label]
 if not rs: continue
 psummary.append({'command':label,'observed_rss_max_bytes':max(r.get('VmRSS_bytes',0) for r in rs),'observed_pss_max_bytes':max(r.get('pss_bytes',0) for r in rs),'observed_hwm_max_bytes':max(r.get('VmHWM_bytes',0) for r in rs),'observed_cpu_user_s':max(r.get('cpu_user_s',0) for r in rs),'observed_cpu_system_s':max(r.get('cpu_system_s',0) for r in rs),'observed_fd_max':max(r.get('fd_count',0) for r in rs),'observed_threads_max':max(r.get('threads',0) for r in rs)})
result={'scope':meta['scope'],'baseline_sha':meta['baseline_sha'],'seed':meta['seed'],'totals':{'main_scenarios':len(mainh),'main_requests':expected_requests,'main_persists':sum(r['persist_calls'] for r in mainio),'all_requests':len(requests),'all_persists':len(persists),'raw_benchmark_rows':len(bench),'command_receipts':len(commands)},'benchmarks':bsummary,'http':hsummary,'process_samples':psummary,'release_gate':'FAIL_OR_UNKNOWN_NOT_PASS'}
(out/'SUMMARY.json').write_text(json.dumps(result,indent=2)+'\n')
for name,rows in [('BENCH_MEDIANS',bsummary),('HTTP_MEDIANS',hsummary),('PROCESS_PEAKS',psummary)]:
 with (out/(name+'.csv')).open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(rows[0]),lineterminator='\n'); w.writeheader(); w.writerows(rows)
lines=['# Rdev isolated baseline — measured, not release PASS','',f"Task t_f44014f8; baseline production source SHA `{meta['baseline_sha']}`.",f"Toolchain: {meta['go']}; synthetic data seed {meta['seed']}. Fixture event timestamps frozen at 2026-09-30T00:00:00Z; ephemeral signing keys/lease secrets random and never logged.", '', '## Scope and reproduction','', '`python3 scripts/perfdiag/run_baseline.py --out <absolute-output-directory> --scratch <absolute-profile-scratch>`','', 'No online connection, production state, actual host or production implementation changes. The harness uses real MemoryGateway/FileStateStore and nonpreview event-poll HTTP handlers; no alternate persistence implementation. GOMAXPROCS=2, GOMEMLIMIT=512MiB soft runtime limit, go -p=1, GOPROXY/GOSUMDB off. Shared Linux host has 4 logical AMD EPYC CPUs; environment.json carries memory/cgroup facts. Timing setup and verification excluded from benchmem; whole-command profiles include fixture setup/verification and must not be read as pure per-operation percentages. HTTP direct-handler timings exclude TCP/network/MCP/host and use zero long-poll wait. No task dispatch/ACK/result measurement is claimed.', '',f"Three repetitions of {len(meta['history_counts'])} audit sizes × {len(meta['client_counts'])} active endpoint counts = {len(mainh)} main scenarios, {expected_requests} requests and exactly {expected_requests} persist calls. One client = one synthetic session = one endpoint; endpoint-directory count is not used as an active-client proxy. Workload is closed-loop burst with {meta['polls_per_client']} polls/client, not a fixed arrival rate or production duty cycle.",'','## Go benchmem (three-repeat median; absolute values)','','| Seam / history | ns/op | B/op | allocs/op |','|---|---:|---:|---:|']
for r in bsummary: lines.append(f"| {r['benchmark']} | {r['ns_per_op_median']:.0f} | {r['bytes_per_op_median']:.0f} | {r['allocs_per_op_median']:.0f} |")
lines += ['','Event-only control holds audit=2, sessions=1, endpoints=1 while growing actual status event/idempotency history. It independently tests the control-plane clone/JSON cost. Task history was not independently varied.','', '## Concurrent nonpreview poll and IO (median of three distributions, not pooled percentiles)','','| Audit history | active clients | p95 ms | p99 ms | req/s | allocated B/request | emitted B/persist | /proc write_bytes B/persist | frozen handler budget |','|---:|---:|---:|---:|---:|---:|---:|---:|---|']
for r in hsummary: lines.append(f"| {r['history']} | {r['clients']} | {r['p95_ms_median']:.3f} | {r['p99_ms_median']:.3f} | {r['requests_per_s_median']:.2f} | {r['alloc_bytes_per_request_median']:.1f} | {r['snapshot_bytes_per_persist_median']:.1f} | {r['write_bytes_per_persist_median']:.1f} | {r['handler_budget_status']} |")
lines += ['', 'Every poll renews one lease and synchronously calls real FileStateStore.SaveFrom once. Test-only decorator captures save latency, resulting snapshot size, /proc/self/io wchar and write_bytes before/after each save without changing the underlying writer/state locks. Process-level physical IO can include concurrent handler work and kernel block rounding, not exact device fsync durability. Snapshots emitted per second and byte totals are absolute raw metrics. It is not valid to compare these short-burst throughput rates with the operator-reported production sustained ~45MB/s as equivalent workloads.', '', '| Audit history | clients | persists/request | rewrite bytes / net state-file growth | net file growth B | write_bytes B/s |', '|---:|---:|---:|---:|---:|---:|']
for r in hsummary: lines.append(f"| {r['history']} | {r['clients']} | {r['persists_per_request_median']:.1f} | {r['emitted_to_netgrowth_median']:.1f} | {r['net_file_growth_bytes_median']:.0f} | {r['write_bytes_per_s_median']:.0f} |")
lines += ['', 'Amplification denominator is net snapshot file-size growth across the measured burst, NOT true logical changed-record bytes; zero/negative net growth is reported as null. Lease grace-secret retention grows the file at fixed test clock. Exact per-persist bytes/count/frequency are in PERSIST_SAMPLES and IO_SUMMARIES JSON/CSV. IO amplification and per-save allocation, not only RSS, are the release-critical finding.', '', '## Process resource observations (not gateway steady-state SLO)','','| Command | observed RSS max B | observed PSS max B | sampled user CPU s | sampled system CPU s | FD max |','|---|---:|---:|---:|---:|---:|']
for r in psummary: lines.append(f"| {r['command']} | {r['observed_rss_max_bytes']} | {r['observed_pss_max_bytes']} | {r['observed_cpu_user_s']:.2f} | {r['observed_cpu_system_s']:.2f} | {r['observed_fd_max']} |")
lines += ['', 'Samples every 100ms measure the direct test binary, not the compiler tree. These are observed maxima/HWM and may miss sub-100ms transients. Test fixtures retain comparison snapshots and validation buffers; none of these small-history observations proves a 700k cold-recovery peak, steady-state RSS p95 or bounded long-term growth. HTTP_SUMMARIES holds real heap-before/after, totalalloc, GC count/pause totals and goroutine counts. Profile inuse_space is sampled test-process memory, not live gateway retained heap. Network bytes are N/A for direct handler calls, not measured zero.', '', '## Evidence and gate status','','commands.json preserves every argv/cwd/env/exit/elapsed/cgroup before/after. Raw BENCH_RESULTS, HTTP_REQUESTS, HTTP_SUMMARIES, PERSIST_SAMPLES, IO_SUMMARIES and PROCESS_SAMPLES JSON/CSV are authoritative. Profile .pprof files are synthetic-only local artifacts; text top outputs identify call stacks. Expected diagnostic RED tests have exit1; runner exit0 means evidence collection succeeded, NOT that SLOs passed. Positive fixture/matrix tests verify JSON roundtrip, audit/event count+sequence, session/endpoint/lease restoration and permissions.', '', 'This card delivers TASK_PACK A/B baseline portions only. It does NOT supply before/after optimized GREEN, full-scale ~700k/1.4m, >=60-minute baseline/candidate soak, actual MCP/managed-host ACK+RTT, fault-injection durability, migration/rollback, real Windows verification, final candidate/CI or deployment. These remain independent downstream gates. Operator reports SIGKILL was panel-manual, not OOM; kill attribution is supplied context, not independent investigation. The operator-provided ops archive statistical CSV was subsequently read and exact window rate calculated: see OPS_WINDOW.md (21 samples over599.842782s, write delta23,150,555,136B). This supersedes uptime-derived~45MB/s estimates; no production state/profile was accessed.','']
(out/'BASELINE.md').write_text('\n'.join(lines))
print(json.dumps(result,indent=2))
