#!/usr/bin/env bash
set -euo pipefail

plan=""

usage() {
  cat >&2 <<'USAGE'
usage: scripts/github/verify-post-release-install-plan.sh --plan PATH

Verifies rdev.post-release-install-plan.v1 generated by
scripts/github/plan-post-release-install.sh. The verifier is local-only: it
does not download release assets, execute install scripts, publish to GitHub,
or mutate external state.

Options:
  --plan PATH  post-release-install-plan.json
  -h, --help   Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --plan)
      plan="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "unknown option: $1" >&2
      usage
      exit 2
      ;;
    *)
      echo "unexpected argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if [[ -z "$plan" ]]; then
  usage
  exit 2
fi

plan_abs="$(python3 - "$plan" <<'PY'
import pathlib, sys
print(pathlib.Path(sys.argv[1]).expanduser().resolve())
PY
)"
if [[ ! -f "$plan_abs" ]]; then
  echo "post-release install plan not found: $plan_abs" >&2
  exit 1
fi

python3 - "$plan_abs" <<'PY'
import datetime
import json
import pathlib
import re
import sys

plan_path = pathlib.Path(sys.argv[1])
try:
    plan = json.loads(plan_path.read_text())
except Exception as exc:
    raise SystemExit(f"failed to parse plan JSON: {exc}") from exc

checks = []

def add(name, ok, detail=""):
    checks.append({"name": name, "ok": bool(ok), "detail": detail})
    return bool(ok)

def sha_ok(value):
    if not isinstance(value, str):
        return False
    if value.startswith("sha256:"):
        value = value.split(":", 1)[1]
    return bool(re.fullmatch(r"[0-9a-fA-F]{64}", value))

plan_dir = plan_path.parent

def resolve_plan_path(path_value):
    path = pathlib.Path(path_value or ".")
    if not path.is_absolute():
        path = plan_dir / path
    return path

def read_file(path_value):
    try:
        path = resolve_plan_path(path_value)
        return path, path.read_text(encoding="utf-8")
    except Exception as exc:
        return resolve_plan_path(path_value), None

def has_forbidden_side_effects(text):
    forbidden = [
        "gh release create",
        "gh release upload",
        "gh repo create",
        "git push",
        "git merge",
        "git tag",
        "New-Service",
        "Register-ScheduledTask",
        "Set-ExecutionPolicy",
        "launchctl",
        "systemctl",
        "sc.exe create",
        "Start-Service",
    ]
    return [needle for needle in forbidden if needle in text]

schema_ok = add("schema_version", plan.get("schema_version") == "rdev.post-release-install-plan.v1", str(plan.get("schema_version")))
add("external_mutation_false", plan.get("external_mutation") is False, str(plan.get("external_mutation")))

repo = plan.get("repo") or ""
tag = plan.get("tag") or ""
download_base = plan.get("asset_download_base") or ""
release_url = plan.get("release_url") or ""
add("repo_present", bool(repo), repo)
add("tag_present", bool(tag), tag)
add("download_base_contains_repo_and_tag", repo in download_base and tag in download_base, download_base)
add("release_url_contains_repo_and_tag", repo in release_url and tag in release_url, release_url)

source_release_plan = pathlib.Path(plan.get("source_release_plan") or "")
if add("source_release_plan_exists", source_release_plan.is_file(), str(source_release_plan)):
    try:
        release_plan = json.loads(source_release_plan.read_text())
    except Exception as exc:
        release_plan = {}
        add("source_release_plan_parse", False, str(exc))
    else:
        add("source_release_plan_schema", release_plan.get("schema_version") == "rdev.github-platform-release-plan.v1", str(release_plan.get("schema_version")))
else:
    release_plan = {}

documents = plan.get("documents") or {}
verify_doc_path, verify_doc_text = read_file(documents.get("verify_install", ""))
add("verify_install_doc_exists", verify_doc_text is not None, str(verify_doc_path))
commands_path, commands_text = read_file(documents.get("commands", ""))
add("commands_file_exists", commands_text is not None, str(commands_path))
if verify_doc_text is not None:
    add("verify_install_mentions_no_unverified_host", "Do not run `rdev-host`" in verify_doc_text, str(verify_doc_path))
if commands_text is not None:
    add("commands_file_no_forbidden_side_effects", not has_forbidden_side_effects(commands_text), ",".join(has_forbidden_side_effects(commands_text)))

platforms = plan.get("platforms") or []
add("platforms_present", bool(platforms), str(len(platforms)))
seen_targets = set()
for index, platform in enumerate(platforms):
    target = platform.get("target") or ""
    prefix = f"platform[{index}]"
    add(f"{prefix}.target_present", bool(target), target)
    add(f"{prefix}.target_unique", target not in seen_targets, target)
    seen_targets.add(target)
    language = platform.get("verification_language")
    script = pathlib.Path(platform.get("verification_script") or "")
    archive = platform.get("archive") or {}
    commands = platform.get("commands") or []
    command_text = "\n".join(commands) + ("\n" if commands else "")
    script_path, script_text = read_file(str(script))
    add(f"{prefix}.script_exists", script_text is not None, str(script_path))
    add(f"{prefix}.script_inside_plan_dir", plan_dir in script_path.parents or script_path == plan_dir, str(script_path))
    if script_text is not None:
        add(f"{prefix}.script_matches_commands", script_text == command_text, str(script_path))
        add(f"{prefix}.script_no_forbidden_side_effects", not has_forbidden_side_effects(script_text), ",".join(has_forbidden_side_effects(script_text)))
    add(f"{prefix}.download_url_matches_base", str(archive.get("download_url", "")).startswith(download_base + "/"), str(archive.get("download_url", "")))
    add(f"{prefix}.archive_sha256_valid", sha_ok(archive.get("sha256", "")) and sha_ok(archive.get("sha256_hex", "")), str(archive.get("sha256", "")))
    add(f"{prefix}.root_public_key_present", bool(platform.get("root_public_key")), "")
    add(f"{prefix}.required_artifacts_present", bool(platform.get("required_artifacts")), ",".join(platform.get("required_artifacts") or []))
    add(f"{prefix}.commands_include_release_verify_candidate", "release" in command_text and "verify-candidate" in command_text, "")
    add(f"{prefix}.commands_include_bundle_verify", "rdev-verify" in command_text and "--bundle" in command_text, "")
    add(f"{prefix}.commands_include_archive_checksum", "shasum -a 256 -c -" in command_text or "Get-FileHash -Algorithm SHA256" in command_text, "")
    if target.startswith("windows/"):
        add(f"{prefix}.language_windows_powershell", language == "powershell" and script.suffix.lower() == ".ps1", f"{language} {script}")
        add(f"{prefix}.windows_uses_expand_archive", "Expand-Archive" in command_text, "")
    else:
        add(f"{prefix}.language_unix_bash", language == "bash" and script.suffix == ".sh", f"{language} {script}")
        add(f"{prefix}.unix_uses_tar_extract", "tar -xzf" in command_text, "")

skillkit = plan.get("skillkit") or {}
skillkit_archive = skillkit.get("archive") or {}
skillkit_script = pathlib.Path(skillkit.get("verification_script") or "")
skillkit_path, skillkit_text = read_file(str(skillkit_script))
add("skillkit_archive_present", bool(skillkit_archive.get("name")), str(skillkit_archive.get("name", "")))
add("skillkit_archive_sha256_valid", sha_ok(skillkit_archive.get("sha256", "")) and sha_ok(skillkit_archive.get("sha256_hex", "")), str(skillkit_archive.get("sha256", "")))
add("skillkit_script_exists", skillkit_text is not None, str(skillkit_path))
add("skillkit_script_inside_plan_dir", plan_dir in skillkit_path.parents or skillkit_path == plan_dir, str(skillkit_path))
if skillkit_text is not None:
    add("skillkit_script_matches_commands", skillkit_text == "\n".join(skillkit.get("commands") or []) + "\n", str(skillkit_path))
    add("skillkit_script_runs_skillkit_verify", "rdev skillkit verify --bundle" in skillkit_text, "")
    add("skillkit_script_no_forbidden_side_effects", not has_forbidden_side_effects(skillkit_text), ",".join(has_forbidden_side_effects(skillkit_text)))

global_assets = plan.get("global_assets") or []
global_kinds = {asset.get("kind", "") for asset in global_assets}
for kind in ["platform-release-index", "platform-release-verification", "install-guide", "skillkit-archive"]:
    add(f"global_asset_{kind}_present", kind in global_kinds, ",".join(sorted(global_kinds)))
for index, asset in enumerate(global_assets):
    add(f"global_asset[{index}].download_url_matches_base", str(asset.get("download_url", "")).startswith(download_base + "/"), str(asset.get("download_url", "")))
    add(f"global_asset[{index}].sha256_valid", sha_ok(asset.get("sha256", "")) and sha_ok(asset.get("sha256_hex", "")), str(asset.get("sha256", "")))

ok = all(check["ok"] for check in checks)
result = {
    "schema_version": "rdev.post-release-install-verification.v1",
    "generated_at": datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
    "ok": ok,
    "plan": str(plan_path.resolve()),
    "repo": repo,
    "tag": tag,
    "platform_count": len(platforms),
    "check_count": len(checks),
    "failed_checks": [check for check in checks if not check["ok"]],
    "checks": checks,
    "external_mutation": False,
}
print(json.dumps(result, indent=2))
if not ok:
    sys.exit(1)
PY
