package supportsession

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"

	"github.com/EitanWong/remote-dev-skillkit/internal/hostcap"
	"github.com/EitanWong/remote-dev-skillkit/internal/model"
	"github.com/EitanWong/remote-dev-skillkit/internal/policy"
)

const PlanSchemaVersion = "rdev.support-session-plan.v1"
const PrepareSchemaVersion = "rdev.support-session-prepare.v1"
const CreatedSchemaVersion = "rdev.support-session-created.v1"
const StartedSchemaVersion = "rdev.support-session-started.v1"
const StatusSchemaVersion = "rdev.support-session-status.v1"
const ConnectionAttemptPolicySchemaVersion = "rdev.connection-attempt-policy.v1"
const UserHandoffSchemaVersion = "rdev.support-session-user-handoff.v1"

const (
	targetHTTPConnectTimeoutSeconds = 2
	targetHTTPMaxTimeSeconds        = 10
	targetHTTPRetries               = 1
	targetHTTPRetryDelaySeconds     = 1
)

type Options struct {
	RepoRoot    string
	WorkDir     string
	GatewayURL  string
	Addr        string
	Target      string
	Reason      string
	TTLSeconds  int
	AutoApprove bool
	Locale      string
}

type PrepareOptions struct {
	RepoRoot    string
	WorkDir     string
	Addr        string
	GatewayURL  string
	Target      string
	BuildAssets bool
}

type GatewayURLCandidate struct {
	URL         string `json:"url"`
	Kind        string `json:"kind"`
	Scope       string `json:"scope"`
	Host        string `json:"host"`
	Port        string `json:"port"`
	Recommended bool   `json:"recommended"`
	Reason      string `json:"reason"`
}

type StatusOptions struct {
	TicketCode string
	Hosts      []model.Host
	Locale     string
}

type CreatedOptions struct {
	GatewayURL            string
	GatewayURLCandidates  []GatewayURLCandidate
	JoinURL               string
	ManifestURL           string
	ManifestRootPublicKey string
	Ticket                model.Ticket
	Target                string
	Locale                string
	RdevCommand           string
	AutoApprove           bool
}

type StartedOptions struct {
	Addr                    string
	GatewayURL              string
	WorkDir                 string
	Created                 map[string]any
	AssetReport             any
	ConnectionReadiness     any
	ConnectivityStrategy    any
	StandardRecoveryActions []string
}

func BuildStarted(opts StartedOptions) map[string]any {
	addr := strings.TrimSpace(opts.Addr)
	gatewayURL := strings.TrimRight(strings.TrimSpace(opts.GatewayURL), "/")
	workDir := strings.TrimSpace(opts.WorkDir)
	return map[string]any{
		"schema_version": StartedSchemaVersion,
		"ok":             true,
		"intent":         "foreground-local-gateway-plus-one-command-support-session",
		"gateway": map[string]any{
			"addr":        addr,
			"gateway_url": gatewayURL,
			"work_dir":    workDir,
			"lifecycle":   "foreground-visible-process",
			"stop":        "interrupt this rdev support-session start process",
		},
		"session":               opts.Created,
		"asset_report":          opts.AssetReport,
		"connection_readiness":  opts.ConnectionReadiness,
		"connectivity_strategy": opts.ConnectivityStrategy,
		"agent_flow": []string{
			"keep this process running while the target host connects",
			"give the target-side human only session.target_command or session.join_url",
			"watch connection status with session.watch_connection_status or rdev.support_session.status",
			"when connected=true, proactively report that the connection is established",
			"if connection_readiness.ready is false, follow standard_recovery_actions instead of writing ad hoc bootstrap or relay code",
		},
		"standard_recovery_actions": standardRecoveryActions(opts.StandardRecoveryActions),
		"forbidden": []string{
			"background hidden gateway",
			"ExecutionPolicy Bypass",
			"manual ticket/root/gateway/transport assembly for target user",
			"ad hoc bootstrap script generated by the Agent",
		},
	}
}

func Prepare(ctx context.Context, opts PrepareOptions) (map[string]any, error) {
	addr := strings.TrimSpace(opts.Addr)
	if addr == "" {
		addr = "0.0.0.0:8787"
	}
	gatewayURL, gatewayCandidates := ResolveGatewayURL(addr, opts.GatewayURL)
	repoRootInput := strings.TrimSpace(opts.RepoRoot)
	if repoRootInput == "" {
		repoRootInput = "."
	}
	repoRoot, err := filepath.Abs(repoRootInput)
	if err != nil {
		repoRoot = repoRootInput
	}
	if found := findRepoRoot(repoRoot); found != "" {
		repoRoot = found
	} else if wd, err := os.Getwd(); err == nil {
		if found := findRepoRoot(wd); found != "" {
			repoRoot = found
		}
	}
	workDir := strings.TrimSpace(opts.WorkDir)
	if workDir == "" {
		workDir = filepath.Join(repoRoot, "work", "rdev-support-session")
	}
	workDir, err = filepath.Abs(workDir)
	if err != nil {
		return nil, err
	}
	binDir := filepath.Join(workDir, "bin")
	goPath, _ := exec.LookPath("go")
	gitPath, _ := exec.LookPath("git")
	rdevPath, _ := exec.LookPath("rdev")
	currentExecutable, _ := os.Executable()
	repoValid := pathExists(filepath.Join(repoRoot, "go.mod")) && pathExists(filepath.Join(repoRoot, "cmd", "rdev", "main.go"))
	assets := supportSessionAssetSpecs(binDir)
	missingInputs := []string{}
	if strings.TrimSpace(goPath) == "" {
		missingInputs = append(missingInputs, "go binary is required to build missing helper assets from source")
	}
	if !repoValid {
		missingInputs = append(missingInputs, "valid remote-dev-skillkit checkout with go.mod and cmd/rdev/main.go")
	}
	assetReports := make([]map[string]any, 0, len(assets))
	allAssetsReady := true
	for _, asset := range assets {
		assetReady := false
		report := map[string]any{
			"id":           asset.ID,
			"goos":         asset.GOOS,
			"goarch":       asset.GOARCH,
			"path":         asset.Path,
			"asset_url":    gatewayURL + "/assets/" + asset.Name,
			"sha256_url":   gatewayURL + "/assets/" + asset.Name + ".sha256",
			"build_status": "not-requested",
		}
		if fileExists(asset.Path) {
			sum, err := fileSHA256Hex(asset.Path)
			if err != nil {
				report["present"] = false
				report["error"] = err.Error()
			} else {
				report["present"] = true
				report["sha256"] = sum
				assetReady = true
			}
			if !assetReady {
				allAssetsReady = false
			}
			assetReports = append(assetReports, report)
			continue
		}
		report["present"] = false
		if opts.BuildAssets && repoValid && strings.TrimSpace(goPath) != "" {
			if err := os.MkdirAll(filepath.Dir(asset.Path), 0o700); err != nil {
				report["build_status"] = "failed"
				report["error"] = err.Error()
				assetReports = append(assetReports, report)
				continue
			}
			cmd := exec.CommandContext(ctx, goPath, "build", "-o", asset.Path, "./cmd/rdev")
			cmd.Dir = repoRoot
			cmd.Env = append(os.Environ(), "GOOS="+asset.GOOS, "GOARCH="+asset.GOARCH, "CGO_ENABLED=0")
			output, err := cmd.CombinedOutput()
			if err != nil {
				report["build_status"] = "failed"
				report["error"] = err.Error()
				if len(output) > 0 {
					report["build_output_tail"] = tailString(string(output), 800)
				}
				assetReports = append(assetReports, report)
				continue
			}
			sum, err := fileSHA256Hex(asset.Path)
			if err != nil {
				report["build_status"] = "failed"
				report["error"] = err.Error()
				assetReports = append(assetReports, report)
				continue
			}
			report["present"] = true
			report["build_status"] = "built"
			report["sha256"] = sum
			assetReady = true
		}
		if !assetReady {
			allAssetsReady = false
		}
		assetReports = append(assetReports, report)
	}
	localRdevUsable := strings.TrimSpace(rdevPath) != ""
	if !localRdevUsable && strings.TrimSpace(currentExecutable) != "" && strings.Contains(filepath.Base(currentExecutable), "rdev") {
		localRdevUsable = true
		rdevPath = currentExecutable
	}
	target := normalizeTarget(opts.Target)
	connectionReadiness := map[string]any{
		"ready":                         localRdevUsable || allAssetsReady,
		"local_rdev_usable":             localRdevUsable,
		"target_bootstrap_self_repair":  allAssetsReady,
		"gateway_url":                   gatewayURL,
		"gateway_url_candidates":        gatewayCandidates,
		"target":                        target,
		"human_gets_one_command":        true,
		"auto_approval_contract":        "attended-temporary first host only when created by support-session start/create",
		"requires_human_decision_first": []string{"company or owner authorization when the target is not clearly operator-owned"},
	}
	recoveryActions := []string{
		"prefer rdev support-session start when no gateway is running; it creates the ticket, prints one target command, and watches through support-session status",
		"if local_rdev_usable is false, run go install ./cmd/rdev from a valid checkout or use go run ./cmd/rdev bootstrap agent-plan --repo-root . as a temporary planner",
		"if target_bootstrap_self_repair is false, rerun rdev support-session prepare --build-assets from a valid checkout before giving commands to targets that may not have rdev installed",
		"do not write custom PowerShell, relay, approval polling, ticket substitution, or bootstrap glue",
	}
	return map[string]any{
		"schema_version":         PrepareSchemaVersion,
		"ok":                     true,
		"repo_root":              repoRoot,
		"repo_root_valid":        repoValid,
		"work_dir":               workDir,
		"bin_dir":                binDir,
		"addr":                   addr,
		"gateway_url":            gatewayURL,
		"gateway_url_candidates": gatewayCandidates,
		"detected": map[string]any{
			"os":                 runtime.GOOS,
			"arch":               runtime.GOARCH,
			"go_path":            goPath,
			"git_path":           gitPath,
			"rdev_path":          rdevPath,
			"current_executable": currentExecutable,
			"host_capabilities":  hostcap.Detect(ctx),
		},
		"asset_report": map[string]any{
			"schema_version": "rdev.support-session-assets.v1",
			"build_assets":   opts.BuildAssets,
			"all_ready":      allAssetsReady,
			"assets":         assetReports,
		},
		"connectivity_strategy":  connectivityStrategy(gatewayURL, target, gatewayCandidates),
		"connection_readiness":   connectionReadiness,
		"missing_inputs":         missingInputs,
		"standard_recovery":      recoveryActions,
		"target_handoff_policy":  "give the target-side human only the generated target_command or join_url",
		"forbidden":              []string{"ExecutionPolicy Bypass", "hidden install", "manual ticket/root/gateway/transport assembly", "ad hoc bootstrap code"},
		"recommended_next_step":  recommendedSupportSessionNextStep(localRdevUsable, allAssetsReady),
		"command_to_start":       []string{"rdev", "support-session", "start", "--addr", addr, "--gateway-url", gatewayURL, "--target", target},
		"command_to_prepare_all": []string{"rdev", "support-session", "prepare", "--build-assets", "--addr", addr, "--gateway-url", gatewayURL, "--target", target},
	}, nil
}

func connectivityStrategy(gatewayURL, target string, gatewayCandidates []GatewayURLCandidate) map[string]any {
	return map[string]any{
		"schema_version":         "rdev.support-session-connectivity-strategy.v1",
		"intent":                 "adaptive-connectivity-with-automatic-native-fallback-and-configured-helper-escalation",
		"gateway_url":            gatewayURL,
		"gateway_url_candidates": gatewayCandidates,
		"target":                 target,
		"selection_order": []string{
			"same-machine-local-mcp",
			"native-direct-gateway",
			"native-lan-gateway",
			"proxy-aware-https",
			"wss-then-long-poll-then-poll",
			"existing-ssh-tunnel",
			"existing-frp-or-chisel-relay",
			"existing-headscale-tailscale-mesh",
			"existing-wireguard-vpn",
			"operator-provided-hosted-gateway",
		},
		"automatic_downgrade": []string{
			"if WSS is blocked, rdev host serve --transport auto falls back to HTTPS long-poll",
			"if long-poll is blocked or unstable, rdev host serve --transport auto falls back to short polling",
			"if a direct gateway health check fails, try LAN/private gateway candidates and configured proxy variables before helper paths",
			"if a configured helper path fails, report manual_action_required instead of guessing credentials or mutating network policy",
		},
		"automatic_upgrade": []string{
			"prefer LAN/private gateway when probes show both sides are routed locally",
			"prefer WSS/mTLS-capable gateway when available for lower latency",
			"for owned recurring machines, use a reviewed managed Connection Entry only after explicit persistence approval",
			"after reconnect evidence is available, update runtime memory with the best known stable path for this host",
		},
		"read_only_probes": []string{
			"detect OS and architecture",
			"detect rdev availability",
			"detect proxy environment variable names without logging secret values",
			"probe gateway /healthz and signed manifest reachability",
			"detect ssh, frpc, chisel, tailscale, headscale, and wg/wireguard tools",
			"inspect route/LAN hints only within the operator-approved scope",
		},
		"auto_use_when_configured": []string{
			"HTTP(S) proxy environment variables",
			"existing SSH tunnel start argv in RDEV_SSH_TUNNEL_START_ARGV_JSON",
			"existing relay start argv in RDEV_RELAY_START_ARGV_JSON",
			"existing mesh gateway URL in RDEV_MESH_GATEWAY_URL",
			"existing VPN gateway URL in RDEV_VPN_GATEWAY_URL",
		},
		"approval_required_for": []string{
			"installing tunnel, mesh, VPN, driver, service, or firewall components",
			"creating or editing SSH keys/config",
			"opening ports or changing router/NAT/firewall/DNS/routes",
			"using paid hosted relay or cloud resources",
			"turning a temporary third-party session into managed persistence",
		},
		"agent_rule": "use Connection Entry runner metadata for relay/mesh/VPN/SSH execution; never ask the target-side human to assemble low-level flags",
	}
}

func standardRecoveryActions(actions []string) []string {
	if len(actions) > 0 {
		return actions
	}
	return []string{
		"run rdev support-session prepare to inspect local rdev, Go, Git, repository, helper assets, gateway URL, and target command readiness",
		"if rdev is missing, build it from the checkout with go install ./cmd/rdev or go run ./cmd/rdev bootstrap agent-plan --repo-root .",
		"if helper assets are missing, rerun rdev support-session start from a valid checkout so target bootstraps can download verified helpers",
		"ask one concise question only when authorization, persistence approval, privileged network changes, or a real gateway/relay credential is required",
	}
}

func ResolveGatewayURL(addr, explicitGatewayURL string) (string, []GatewayURLCandidate) {
	candidates := GatewayURLCandidatesFromIPs(addr, explicitGatewayURL, localInterfaceIPs())
	for _, candidate := range candidates {
		if candidate.Recommended {
			return candidate.URL, candidates
		}
	}
	if len(candidates) > 0 {
		return candidates[0].URL, candidates
	}
	return strings.TrimRight(strings.TrimSpace(explicitGatewayURL), "/"), candidates
}

func GatewayURLCandidatesFromIPs(addr, explicitGatewayURL string, ips []net.IP) []GatewayURLCandidate {
	addr = strings.TrimSpace(addr)
	if addr == "" {
		addr = "0.0.0.0:8787"
	}
	host, port := splitListenAddress(addr)
	if port == "" {
		port = "8787"
	}
	explicit := strings.TrimRight(strings.TrimSpace(explicitGatewayURL), "/")
	candidates := make([]GatewayURLCandidate, 0, 2+len(ips))
	if explicit != "" {
		candidates = append(candidates, candidateFromURL(explicit, "explicit", "operator-provided", true, "explicit gateway_url supplied by the Agent/operator"))
	}
	if isWildcardHost(host) {
		for _, ip := range sortedPrivateIPs(ips) {
			url := "http://" + net.JoinHostPort(ip.String(), port)
			candidates = append(candidates, GatewayURLCandidate{
				URL:         url,
				Kind:        "lan-private",
				Scope:       "LAN/VPN/routed-private-network",
				Host:        ip.String(),
				Port:        port,
				Recommended: explicit == "" && !hasRecommendedGatewayCandidate(candidates),
				Reason:      "listen address is wildcard; this private interface address is more useful for target machines than 0.0.0.0",
			})
		}
		loopbackURL := "http://" + net.JoinHostPort("127.0.0.1", port)
		candidates = append(candidates, GatewayURLCandidate{
			URL:         loopbackURL,
			Kind:        "loopback",
			Scope:       "same-machine-only",
			Host:        "127.0.0.1",
			Port:        port,
			Recommended: explicit == "" && !hasRecommendedGatewayCandidate(candidates),
			Reason:      "fallback for same-machine testing only; remote target machines cannot use this URL",
		})
		return dedupeGatewayCandidates(candidates)
	}
	urlHost := host
	if urlHost == "" {
		urlHost = "127.0.0.1"
	}
	scope := "host-specific"
	kind := "host"
	reason := "listen address names a concrete host"
	if isLoopbackHost(urlHost) {
		scope = "same-machine-only"
		kind = "loopback"
		reason = "loopback is only suitable when the target is this same machine"
	}
	candidates = append(candidates, GatewayURLCandidate{
		URL:         "http://" + net.JoinHostPort(urlHost, port),
		Kind:        kind,
		Scope:       scope,
		Host:        urlHost,
		Port:        port,
		Recommended: explicit == "",
		Reason:      reason,
	})
	return dedupeGatewayCandidates(candidates)
}

func splitListenAddress(addr string) (string, string) {
	host, port, err := net.SplitHostPort(addr)
	if err == nil {
		return strings.Trim(host, "[]"), port
	}
	if strings.HasPrefix(addr, ":") {
		return "", strings.TrimPrefix(addr, ":")
	}
	if strings.Count(addr, ":") == 0 {
		return addr, ""
	}
	return strings.Trim(addr, "[]"), ""
}

func candidateFromURL(rawURL, kind, scope string, recommended bool, reason string) GatewayURLCandidate {
	host := ""
	port := ""
	withoutScheme := strings.TrimPrefix(strings.TrimPrefix(rawURL, "http://"), "https://")
	if parsedHost, parsedPort, err := net.SplitHostPort(withoutScheme); err == nil {
		host = strings.Trim(parsedHost, "[]")
		port = parsedPort
	}
	return GatewayURLCandidate{
		URL:         rawURL,
		Kind:        kind,
		Scope:       scope,
		Host:        host,
		Port:        port,
		Recommended: recommended,
		Reason:      reason,
	}
}

func localInterfaceIPs() []net.IP {
	var out []net.IP
	ifaces, err := net.Interfaces()
	if err != nil {
		return out
	}
	for _, iface := range ifaces {
		if iface.Flags&net.FlagUp == 0 {
			continue
		}
		addrs, err := iface.Addrs()
		if err != nil {
			continue
		}
		for _, addr := range addrs {
			var ip net.IP
			switch value := addr.(type) {
			case *net.IPNet:
				ip = value.IP
			case *net.IPAddr:
				ip = value.IP
			}
			if ip == nil || !ip.IsPrivate() {
				continue
			}
			out = append(out, normalizeIP(ip))
		}
	}
	return out
}

func sortedPrivateIPs(ips []net.IP) []net.IP {
	values := make([]net.IP, 0, len(ips))
	seen := map[string]bool{}
	for _, ip := range ips {
		ip = normalizeIP(ip)
		if ip == nil || !ip.IsPrivate() {
			continue
		}
		key := ip.String()
		if seen[key] {
			continue
		}
		seen[key] = true
		values = append(values, ip)
	}
	sort.Slice(values, func(i, j int) bool {
		left4 := values[i].To4() != nil
		right4 := values[j].To4() != nil
		if left4 != right4 {
			return left4
		}
		return values[i].String() < values[j].String()
	})
	return values
}

func normalizeIP(ip net.IP) net.IP {
	if ip == nil {
		return nil
	}
	if v4 := ip.To4(); v4 != nil {
		return v4
	}
	return ip
}

func isWildcardHost(host string) bool {
	host = strings.Trim(strings.ToLower(strings.TrimSpace(host)), "[]")
	return host == "" || host == "0.0.0.0" || host == "::" || host == "[::]"
}

func isLoopbackHost(host string) bool {
	host = strings.Trim(strings.ToLower(strings.TrimSpace(host)), "[]")
	return host == "localhost" || host == "127.0.0.1" || host == "::1"
}

func hasRecommendedGatewayCandidate(candidates []GatewayURLCandidate) bool {
	for _, candidate := range candidates {
		if candidate.Recommended {
			return true
		}
	}
	return false
}

func dedupeGatewayCandidates(candidates []GatewayURLCandidate) []GatewayURLCandidate {
	out := make([]GatewayURLCandidate, 0, len(candidates))
	seen := map[string]bool{}
	for _, candidate := range candidates {
		if strings.TrimSpace(candidate.URL) == "" || seen[candidate.URL] {
			continue
		}
		seen[candidate.URL] = true
		out = append(out, candidate)
	}
	return out
}

func dedupeStrings(values []string) []string {
	out := make([]string, 0, len(values))
	seen := map[string]bool{}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, value)
	}
	return out
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func BuildCreated(opts CreatedOptions) map[string]any {
	gatewayURL := strings.TrimRight(strings.TrimSpace(opts.GatewayURL), "/")
	joinURL := strings.TrimSpace(opts.JoinURL)
	if joinURL == "" && gatewayURL != "" && opts.Ticket.Code != "" {
		joinURL = gatewayURL + "/join/" + opts.Ticket.Code
	}
	manifestURL := strings.TrimSpace(opts.ManifestURL)
	if manifestURL == "" && gatewayURL != "" && opts.Ticket.Code != "" {
		manifestURL = gatewayURL + "/v1/tickets/" + opts.Ticket.Code + "/manifest"
	}
	locale := strings.TrimSpace(opts.Locale)
	if locale == "" {
		locale = "auto"
	}
	target := normalizeTarget(opts.Target)
	rdevCommand := strings.TrimSpace(opts.RdevCommand)
	if rdevCommand == "" {
		rdevCommand = "rdev"
	}
	gatewayCandidates := normalizeCreatedGatewayCandidates(gatewayURL, opts.GatewayURLCandidates)
	joinURLs := joinURLsForGatewayCandidates(gatewayCandidates, opts.Ticket.Code)
	if len(joinURLs) == 0 && joinURL != "" {
		joinURLs = []string{joinURL}
	}
	attemptPolicy := connectionAttemptPolicy(gatewayCandidates, joinURLs)
	windowsCommand := windowsBootstrapCommand(joinURLs)
	macLinuxCommand := macLinuxBootstrapCommand(joinURLs)
	targetCommands := map[string]string{
		"windows":     windowsCommand,
		"macos_linux": macLinuxCommand,
		"join_url":    joinURL,
	}
	recommended := joinURL
	recommendedSurface := "join_url"
	switch target {
	case "windows":
		recommended = windowsCommand
		recommendedSurface = "windows"
	case "macos", "linux":
		recommended = macLinuxCommand
		recommendedSurface = "macos_linux"
	}
	statusCommand := []string{
		rdevCommand, "support-session", "status",
		"--gateway-url", gatewayURL,
		"--ticket-code", opts.Ticket.Code,
		"--wait",
		"--locale", locale,
	}
	return map[string]any{
		"schema_version":            CreatedSchemaVersion,
		"ok":                        true,
		"session_mode":              string(model.HostModeAttendedTemporary),
		"intent":                    "agent-created-one-command-visible-support-session",
		"gateway_url":               gatewayURL,
		"gateway_url_candidates":    gatewayCandidates,
		"ticket_code":               opts.Ticket.Code,
		"ticket":                    opts.Ticket,
		"join_url":                  joinURL,
		"manifest_url":              manifestURL,
		"manifest_root_public_key":  opts.ManifestRootPublicKey,
		"target":                    target,
		"locale":                    locale,
		"auto_approve":              opts.AutoApprove,
		"recommended_surface":       recommendedSurface,
		"target_command":            recommended,
		"target_commands":           targetCommands,
		"user_handoff":              userHandoff(locale, target, recommendedSurface, recommended, joinURL, targetCommands),
		"connection_attempt_policy": attemptPolicy,
		"watch_connection_status":   statusCommand,
		"mcp_follow_up": []map[string]any{
			{
				"tool": "rdev.support_session.status",
				"arguments": map[string]any{
					"ticket_code": opts.Ticket.Code,
					"locale":      locale,
					"wait":        true,
				},
			},
		},
		"human_message": localizedCreatedMessage(locale),
		"agent_flow": []string{
			"give the target-side human only target_command or join_url",
			"target_command already tries ordered gateway URL candidates with bounded per-candidate timeouts and retry policy; do not write your own fallback script",
			"watch connection status with watch_connection_status or rdev.support_session.status",
			"when connected=true, proactively report that the connection is established",
			"do not ask the human to assemble ticket, gateway, manifest root, transport, or helper flags",
		},
		"forbidden": []string{
			"ExecutionPolicy Bypass",
			"hidden install",
			"manual ticket/root/gateway/transport assembly for target user",
			"ad hoc bootstrap script generated by the Agent",
		},
	}
}

func userHandoff(locale, target, surface, copyPaste, joinURL string, targetCommands map[string]string) map[string]any {
	return map[string]any{
		"schema_version":      UserHandoffSchemaVersion,
		"locale":              locale,
		"target":              target,
		"copy_paste_kind":     surface,
		"copy_paste":          copyPaste,
		"join_url":            joinURL,
		"message":             localizedUserHandoffMessage(locale, surface),
		"windows_command":     targetCommands["windows"],
		"macos_linux_command": targetCommands["macos_linux"],
		"agent_next_step":     "send message plus copy_paste to the user, then call rdev.support_session.status with wait=true",
		"agent_rule":          "do not rewrite copy_paste, do not ask the user to assemble ticket/root/gateway/transport, and do not add custom polling",
	}
}

func normalizeCreatedGatewayCandidates(gatewayURL string, candidates []GatewayURLCandidate) []GatewayURLCandidate {
	values := make([]GatewayURLCandidate, 0, len(candidates)+1)
	for _, candidate := range candidates {
		candidate.URL = strings.TrimRight(strings.TrimSpace(candidate.URL), "/")
		if candidate.URL == "" {
			continue
		}
		values = append(values, candidate)
	}
	if gatewayURL != "" && len(values) == 0 {
		values = append(values, candidateFromURL(gatewayURL, "explicit", "operator-provided", true, "created support session gateway URL"))
	}
	if !hasRecommendedGatewayCandidate(values) && len(values) > 0 {
		values[0].Recommended = true
	}
	return dedupeGatewayCandidates(values)
}

func joinURLsForGatewayCandidates(candidates []GatewayURLCandidate, ticketCode string) []string {
	if strings.TrimSpace(ticketCode) == "" {
		return nil
	}
	values := make([]string, 0, len(candidates))
	for _, candidate := range candidates {
		base := strings.TrimRight(strings.TrimSpace(candidate.URL), "/")
		if base == "" {
			continue
		}
		values = append(values, base+"/join/"+ticketCode)
	}
	return dedupeStrings(values)
}

func connectionAttemptPolicy(candidates []GatewayURLCandidate, joinURLs []string) map[string]any {
	candidateReports := make([]map[string]any, 0, len(joinURLs))
	for i, joinURL := range joinURLs {
		report := map[string]any{
			"order":    i + 1,
			"join_url": joinURL,
		}
		if i < len(candidates) {
			report["gateway_url"] = candidates[i].URL
			report["kind"] = candidates[i].Kind
			report["scope"] = candidates[i].Scope
			report["recommended"] = candidates[i].Recommended
		}
		candidateReports = append(candidateReports, report)
	}
	return map[string]any{
		"schema_version":               ConnectionAttemptPolicySchemaVersion,
		"candidate_order":              candidateReports,
		"windows_download_timeout_sec": targetHTTPMaxTimeSeconds,
		"curl_connect_timeout_sec":     targetHTTPConnectTimeoutSeconds,
		"curl_max_time_sec":            targetHTTPMaxTimeSeconds,
		"retries_per_candidate":        targetHTTPRetries,
		"retry_delay_sec":              targetHTTPRetryDelaySeconds,
		"target_handoff":               "single visible command; target-side command owns URL fallback, timeout, retry, download, verification, and host startup",
		"agent_rule":                   "do not rewrite, wrap, or expand target_command; watch the returned status tool/command instead",
	}
}

func windowsBootstrapCommand(joinURLs []string) string {
	urls := quotedPowerShellArrayValues(joinURLs, "/bootstrap.ps1")
	return "powershell -NoProfile -Command \"$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue'; $urls=@(" + strings.Join(urls, ",") + "); foreach ($u in $urls) { try { irm $u -UseBasicParsing -TimeoutSec " + strconv.Itoa(targetHTTPMaxTimeSeconds) + " | iex; exit 0 } catch { Write-Host ('rdev Connection Entry failed: ' + $u) } }; throw 'No reachable rdev Connection Entry URL'\""
}

func macLinuxBootstrapCommand(joinURLs []string) string {
	urls := quotedShellArrayValues(joinURLs, "/bootstrap.sh")
	return "sh -c 'set -eu; t=\"${TMPDIR:-/tmp}/rdev-bootstrap-$$.sh\"; for u in " + strings.Join(urls, " ") + "; do if curl --connect-timeout " + strconv.Itoa(targetHTTPConnectTimeoutSeconds) + " --max-time " + strconv.Itoa(targetHTTPMaxTimeSeconds) + " --retry " + strconv.Itoa(targetHTTPRetries) + " --retry-delay " + strconv.Itoa(targetHTTPRetryDelaySeconds) + " -fsSL \"$u\" -o \"$t\" && sh \"$t\"; then rm -f \"$t\"; exit 0; fi; rm -f \"$t\"; done; echo \"No reachable rdev Connection Entry URL\" >&2; exit 1'"
}

func quotedPowerShellArrayValues(values []string, suffix string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimRight(strings.TrimSpace(value), "/")
		if value == "" {
			continue
		}
		out = append(out, "'"+strings.ReplaceAll(value+suffix, "'", "''")+"'")
	}
	return out
}

func quotedShellArrayValues(values []string, suffix string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimRight(strings.TrimSpace(value), "/")
		if value == "" {
			continue
		}
		out = append(out, shellQuote(value+suffix))
	}
	return out
}

func BuildPlan(ctx context.Context, opts Options) map[string]any {
	repoRootInput := strings.TrimSpace(opts.RepoRoot)
	if repoRootInput == "" {
		repoRootInput = "."
	}
	repoRoot, _ := filepath.Abs(repoRootInput)
	workDir := strings.TrimSpace(opts.WorkDir)
	if workDir == "" {
		workDir = filepath.Join(repoRoot, "work", "rdev-support-session")
	}
	workDir, _ = filepath.Abs(workDir)
	addr := strings.TrimSpace(opts.Addr)
	if addr == "" {
		addr = "0.0.0.0:8787"
	}
	gatewayURL, gatewayCandidates := ResolveGatewayURL(addr, opts.GatewayURL)
	target := strings.TrimSpace(opts.Target)
	if target == "" {
		target = "auto"
	}
	locale := strings.TrimSpace(opts.Locale)
	if locale == "" {
		locale = "auto"
	}
	ttl := opts.TTLSeconds
	if ttl == 0 {
		ttl = 7200
	}
	rdevPath := filepath.Join(workDir, "bin", exeName("rdev", runtime.GOOS))
	windowsRdevPath := filepath.Join(workDir, "bin", "rdev-windows-amd64.exe")
	linuxRdevPath := filepath.Join(workDir, "bin", "rdev-linux-amd64")
	linuxArmRdevPath := filepath.Join(workDir, "bin", "rdev-linux-arm64")
	darwinArmRdevPath := filepath.Join(workDir, "bin", "rdev-darwin-arm64")
	darwinAmdRdevPath := filepath.Join(workDir, "bin", "rdev-darwin-amd64")
	createInviteCommand := []string{
		rdevPath, "invite", "create",
		"--gateway", gatewayURL,
		"--mode", string(model.HostModeAttendedTemporary),
		"--ttl-seconds", strconv.Itoa(ttl),
		"--reason", opts.Reason,
		"--transport", "auto",
	}
	if opts.AutoApprove {
		createInviteCommand = append(createInviteCommand, "--auto-approve")
	}
	inviteBody, _ := json.Marshal(map[string]any{
		"mode":         string(model.HostModeAttendedTemporary),
		"ttl_seconds":  ttl,
		"reason":       opts.Reason,
		"auto_approve": opts.AutoApprove,
		"metadata": map[string]string{
			"connection_entry":  "standard-visible",
			"approval_contract": "target-consent-scoped-ticket",
		},
	})
	return map[string]any{
		"schema_version":         PlanSchemaVersion,
		"ok":                     true,
		"intent":                 "one-command-visible-attended-temporary-connection-entry",
		"repo_root":              repoRoot,
		"work_dir":               workDir,
		"target":                 target,
		"locale":                 locale,
		"gateway_url":            gatewayURL,
		"gateway_url_candidates": gatewayCandidates,
		"auto_approve": map[string]any{
			"enabled":        opts.AutoApprove,
			"scope":          "attended-temporary tickets created by this standard plan only",
			"capabilities":   policyCapabilitiesToStrings(policy.TemporaryDefaults()),
			"security_model": "target consent plus signed manifest plus scoped ticket capabilities",
		},
		"commands": map[string]any{
			"prepare_dirs":           []string{"mkdir", "-p", filepath.Join(workDir, "bin"), filepath.Join(workDir, ".rdev", "keys"), filepath.Join(workDir, ".rdev", "gateway"), filepath.Join(workDir, ".rdev", "audit")},
			"build_local_rdev":       []string{"go", "build", "-o", rdevPath, "./cmd/rdev"},
			"build_windows_rdev":     []string{"env", "GOOS=windows", "GOARCH=amd64", "CGO_ENABLED=0", "go", "build", "-o", windowsRdevPath, "./cmd/rdev"},
			"build_linux_rdev":       []string{"env", "GOOS=linux", "GOARCH=amd64", "CGO_ENABLED=0", "go", "build", "-o", linuxRdevPath, "./cmd/rdev"},
			"build_linux_arm64_rdev": []string{"env", "GOOS=linux", "GOARCH=arm64", "CGO_ENABLED=0", "go", "build", "-o", linuxArmRdevPath, "./cmd/rdev"},
			"build_macos_arm64_rdev": []string{"env", "GOOS=darwin", "GOARCH=arm64", "CGO_ENABLED=0", "go", "build", "-o", darwinArmRdevPath, "./cmd/rdev"},
			"build_macos_amd64_rdev": []string{"env", "GOOS=darwin", "GOARCH=amd64", "CGO_ENABLED=0", "go", "build", "-o", darwinAmdRdevPath, "./cmd/rdev"},
			"start_gateway": []string{
				rdevPath, "gateway", "serve", "--dev",
				"--addr", addr,
				"--audit-log", filepath.Join(workDir, ".rdev", "audit", "events.jsonl"),
				"--state", filepath.Join(workDir, ".rdev", "gateway", "state.json"),
				"--signing-key", filepath.Join(workDir, ".rdev", "keys", "gateway-signing-key.json"),
				"--manifest-signing-key", filepath.Join(workDir, ".rdev", "keys", "manifest-root-key.json"),
				"--rdev-windows-amd64", windowsRdevPath,
				"--rdev-linux-amd64", linuxRdevPath,
				"--rdev-linux-arm64", linuxArmRdevPath,
				"--rdev-darwin-arm64", darwinArmRdevPath,
				"--rdev-darwin-amd64", darwinAmdRdevPath,
			},
			"create_invite_http": []string{
				"curl", "-fsS", "-X", "POST", gatewayURL + "/v1/tickets",
				"-H", "Content-Type: application/json",
				"-d", string(inviteBody),
			},
			"create_invite_cli": createInviteCommand,
			"watch_connection_status": []string{
				rdevPath, "support-session", "status",
				"--gateway-url", gatewayURL,
				"--ticket-code", "<ticket-code>",
				"--wait",
				"--locale", locale,
			},
		},
		"target_user_instructions": LocalizedTargetInstructions(gatewayURL, locale),
		"agent_flow": []string{
			"run prepare_dirs and build commands from repo_root",
			"start gateway with the exact start_gateway argv in a managed terminal/session",
			"create the invite through HTTP or CLI",
			"give target user only the localized join URL or one-line visible script",
			"watch connection status with rdev.support_session.status or rdev support-session status --wait",
			"when connected=true, proactively tell the user the connection is established before creating jobs",
			"do not write ad hoc relay/nohup/bootstrap code",
			"after host connects, it is active when auto_approve is enabled; otherwise call rdev.hosts.approve",
		},
		"forbidden": []string{
			"ExecutionPolicy Bypass",
			"hidden install",
			"unverified binary download",
			"manual ticket/root/gateway/transport assembly for target user",
		},
		"detected_host_capabilities": hostcap.Detect(ctx),
	}
}

func normalizeTarget(target string) string {
	switch strings.ToLower(strings.TrimSpace(target)) {
	case "windows", "win":
		return "windows"
	case "macos", "mac", "darwin":
		return "macos"
	case "linux":
		return "linux"
	default:
		return "auto"
	}
}

func localizedCreatedMessage(locale string) string {
	switch locale {
	case "zh-CN", "zh":
		return "把 target_command 发给目标电脑上的用户执行；然后持续监听状态，连接建立后主动告诉用户。"
	case "ja":
		return "target_command を対象コンピューターのユーザーに渡して実行してもらい、接続状態を監視して、接続後に報告してください。"
	case "ko":
		return "대상 컴퓨터의 사용자에게 target_command를 실행하게 한 뒤 상태를 감시하고 연결되면 알려 주세요."
	case "es":
		return "Entrega target_command a la persona en el equipo de destino, vigila el estado y avisa cuando la conexion quede establecida."
	case "fr":
		return "Donne target_command a la personne sur l'ordinateur cible, surveille l'etat, puis annonce quand la connexion est etablie."
	case "de":
		return "Gib target_command an die Person am Zielcomputer, uberwache den Status und melde, sobald die Verbindung steht."
	case "pt-BR":
		return "Entregue target_command para a pessoa no computador de destino, acompanhe o status e avise quando a conexao estiver estabelecida."
	default:
		return "Give target_command to the target-side human, watch status, and proactively report when the connection is established."
	}
}

func localizedUserHandoffMessage(locale, surface string) string {
	copyHint := "Run this on the target computer and keep the window open while I connect."
	if surface == "join_url" {
		copyHint = "Open this on the target computer and keep the page or terminal open while I connect."
	}
	switch locale {
	case "zh-CN", "zh":
		if surface == "join_url" {
			return "请在目标电脑上打开下面这个连接。打开后保持页面或终端窗口不要关闭，我会自动等待连接并在连上后告诉你。"
		}
		return "请在目标电脑上运行下面这条命令。运行后保持窗口不要关闭，我会自动等待连接并在连上后告诉你。"
	case "ja":
		if surface == "join_url" {
			return "対象コンピューターで次のリンクを開いてください。接続中はページまたはターミナルを開いたままにしてください。接続後に報告します。"
		}
		return "対象コンピューターで次のコマンドを実行してください。接続中はウィンドウを開いたままにしてください。接続後に報告します。"
	case "ko":
		if surface == "join_url" {
			return "대상 컴퓨터에서 아래 링크를 열어 주세요. 연결되는 동안 페이지나 터미널을 닫지 마세요. 연결되면 알려 드립니다."
		}
		return "대상 컴퓨터에서 아래 명령을 실행해 주세요. 연결되는 동안 창을 닫지 마세요. 연결되면 알려 드립니다."
	case "es":
		if surface == "join_url" {
			return "Abre este enlace en el equipo de destino y deja la pagina o terminal abierta mientras conecto. Avisare cuando este conectado."
		}
		return "Ejecuta este comando en el equipo de destino y deja la ventana abierta mientras conecto. Avisare cuando este conectado."
	case "fr":
		if surface == "join_url" {
			return "Ouvre ce lien sur l'ordinateur cible et garde la page ou le terminal ouvert pendant la connexion. Je te dirai quand c'est connecte."
		}
		return "Execute cette commande sur l'ordinateur cible et garde la fenetre ouverte pendant la connexion. Je te dirai quand c'est connecte."
	case "de":
		if surface == "join_url" {
			return "Offne diesen Link auf dem Zielcomputer und lasse die Seite oder das Terminal wahrend der Verbindung offen. Ich melde mich, sobald es verbunden ist."
		}
		return "Fuhre diesen Befehl auf dem Zielcomputer aus und lasse das Fenster wahrend der Verbindung offen. Ich melde mich, sobald es verbunden ist."
	case "pt-BR":
		if surface == "join_url" {
			return "Abra este link no computador de destino e mantenha a pagina ou o terminal aberto enquanto eu conecto. Avisarei quando estiver conectado."
		}
		return "Execute este comando no computador de destino e mantenha a janela aberta enquanto eu conecto. Avisarei quando estiver conectado."
	default:
		return copyHint
	}
}

func BuildStatus(opts StatusOptions) map[string]any {
	ticketCode := strings.TrimSpace(opts.TicketCode)
	locale := strings.TrimSpace(opts.Locale)
	if locale == "" {
		locale = "auto"
	}
	hosts := append([]model.Host(nil), opts.Hosts...)
	active := hostsByStatus(hosts, model.HostStatusActive)
	pending := hostsByStatus(hosts, model.HostStatusPending)
	revoked := hostsByStatus(hosts, model.HostStatusRevoked)
	connected := len(active) > 0
	waiting := !connected && len(pending) == 0
	status := "waiting"
	if connected {
		status = "connected"
	} else if len(pending) > 0 {
		status = "pending-approval"
	} else if len(revoked) > 0 {
		status = "revoked"
	}
	return map[string]any{
		"schema_version": StatusSchemaVersion,
		"ok":             connected || len(pending) > 0 || waiting,
		"ticket_code":    ticketCode,
		"status":         status,
		"connected":      connected,
		"waiting":        waiting,
		"feedback":       localizedStatusFeedback(status, locale),
		"next_action":    localizedStatusNextAction(status, locale),
		"active_hosts":   active,
		"pending_hosts":  pending,
		"revoked_hosts":  revoked,
		"host_count": map[string]int{
			"active":  len(active),
			"pending": len(pending),
			"revoked": len(revoked),
			"total":   len(hosts),
		},
	}
}

func LocalizedTargetInstructions(gatewayURL, locale string) map[string]any {
	windows := "powershell -NoProfile -Command \"irm '" + gatewayURL + "/join/<ticket-code>/bootstrap.ps1' | iex\""
	macLinux := "curl -fsSL " + gatewayURL + "/join/<ticket-code>/bootstrap.sh | sh"
	labels := map[string]string{
		"auto":  "Open this visible support command on the target computer. Keep the terminal open while the Agent works.",
		"en":    "Open this visible support command on the target computer. Keep the terminal open while the Agent works.",
		"zh-CN": "在目标电脑上运行这条可见的支持命令。Agent 工作期间请保持终端窗口打开。",
		"ja":    "対象コンピューターでこの表示されるサポートコマンドを実行し、Agent の作業中はターミナルを開いたままにしてください。",
		"ko":    "대상 컴퓨터에서 이 표시되는 지원 명령을 실행하고 Agent가 작업하는 동안 터미널을 열어 두세요.",
		"es":    "Ejecuta este comando visible de soporte en el equipo de destino y deja la terminal abierta mientras trabaja el Agent.",
		"fr":    "Executez cette commande d'assistance visible sur l'ordinateur cible et gardez le terminal ouvert pendant que l'Agent travaille.",
		"de":    "Fuhre diesen sichtbaren Support-Befehl auf dem Zielcomputer aus und lasse das Terminal offen, wahrend der Agent arbeitet.",
		"pt-BR": "Execute este comando visivel de suporte no computador de destino e mantenha o terminal aberto enquanto o Agent trabalha.",
	}
	message, ok := labels[locale]
	if !ok {
		message = labels["en"]
	}
	return map[string]any{
		"message":             message,
		"windows":             windows,
		"macos_linux":         macLinux,
		"join_url_template":   gatewayURL + "/join/<ticket-code>",
		"human_receives_only": []string{"localized join URL", "visible one-line script", "or signed package when published"},
	}
}

func hostsByStatus(hosts []model.Host, status model.HostStatus) []model.Host {
	values := make([]model.Host, 0, len(hosts))
	for _, host := range hosts {
		if host.Status == status {
			values = append(values, host)
		}
	}
	return values
}

func localizedStatusFeedback(status, locale string) string {
	switch locale {
	case "zh-CN", "zh":
		switch status {
		case "connected":
			return "连接已经建立，目标主机已在线并可用于受控任务。"
		case "pending-approval":
			return "目标主机已经出现，正在等待审批或自动批准完成。"
		case "revoked":
			return "连接票据或主机已经撤销。"
		default:
			return "还没有检测到目标主机连接，请确认目标机器上的可见命令仍在运行。"
		}
	default:
		switch status {
		case "connected":
			return "Connection established. The target host is online and ready for scoped work."
		case "pending-approval":
			return "The target host has appeared and is waiting for approval or auto-approval to complete."
		case "revoked":
			return "The connection ticket or host has been revoked."
		default:
			return "No target host is connected yet. Keep the visible command running on the target machine."
		}
	}
}

func localizedStatusNextAction(status, locale string) string {
	switch locale {
	case "zh-CN", "zh":
		switch status {
		case "connected":
			return "向用户汇报连接已建立，然后检查主机能力并创建最小权限任务。"
		case "pending-approval":
			return "如果不是标准自动批准会话，请审批预期主机；否则继续等待短暂同步。"
		case "revoked":
			return "创建新的 Connection Entry。"
		default:
			return "继续等待，或检查 gateway 地址、网络可达性和目标命令输出。"
		}
	default:
		switch status {
		case "connected":
			return "Tell the user the connection is established, then inspect capabilities and create the smallest scoped job."
		case "pending-approval":
			return "Approve the expected host if this is not a standard auto-approved session; otherwise wait briefly."
		case "revoked":
			return "Create a new Connection Entry."
		default:
			return "Keep waiting, or check gateway reachability, network path, and target command output."
		}
	}
}

func exeName(name, goos string) string {
	if goos == "windows" {
		return name + ".exe"
	}
	return name
}

func policyCapabilitiesToStrings(caps []policy.Capability) []string {
	values := make([]string, 0, len(caps))
	for _, cap := range caps {
		values = append(values, string(cap))
	}
	return values
}

type supportSessionAssetSpec struct {
	ID     string
	Name   string
	GOOS   string
	GOARCH string
	Path   string
}

func supportSessionAssetSpecs(binDir string) []supportSessionAssetSpec {
	return []supportSessionAssetSpec{
		{ID: "windows-amd64", Name: "rdev-windows-amd64.exe", GOOS: "windows", GOARCH: "amd64", Path: filepath.Join(binDir, "rdev-windows-amd64.exe")},
		{ID: "darwin-arm64", Name: "rdev-darwin-arm64", GOOS: "darwin", GOARCH: "arm64", Path: filepath.Join(binDir, "rdev-darwin-arm64")},
		{ID: "darwin-amd64", Name: "rdev-darwin-amd64", GOOS: "darwin", GOARCH: "amd64", Path: filepath.Join(binDir, "rdev-darwin-amd64")},
		{ID: "linux-amd64", Name: "rdev-linux-amd64", GOOS: "linux", GOARCH: "amd64", Path: filepath.Join(binDir, "rdev-linux-amd64")},
		{ID: "linux-arm64", Name: "rdev-linux-arm64", GOOS: "linux", GOARCH: "arm64", Path: filepath.Join(binDir, "rdev-linux-arm64")},
	}
}

func recommendedSupportSessionNextStep(localRdevUsable, allAssetsReady bool) string {
	switch {
	case localRdevUsable && allAssetsReady:
		return "run rdev support-session start and give the generated target_command to the target-side human"
	case allAssetsReady:
		return "use the current rdev executable or checkout command to run support-session start; target-side self-repair assets are ready"
	default:
		return "prepare helper assets from a valid checkout before relying on one-command targets without preinstalled rdev"
	}
}

func pathExists(path string) bool {
	if strings.TrimSpace(path) == "" {
		return false
	}
	_, err := os.Stat(path)
	return err == nil
}

func findRepoRoot(start string) string {
	if strings.TrimSpace(start) == "" {
		return ""
	}
	dir, err := filepath.Abs(start)
	if err != nil {
		return ""
	}
	info, err := os.Stat(dir)
	if err == nil && !info.IsDir() {
		dir = filepath.Dir(dir)
	}
	for {
		if pathExists(filepath.Join(dir, "go.mod")) && pathExists(filepath.Join(dir, "cmd", "rdev", "main.go")) {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func fileSHA256Hex(path string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:]), nil
}

func tailString(value string, limit int) string {
	if limit <= 0 || len(value) <= limit {
		return value
	}
	return value[len(value)-limit:]
}
