package managedhost

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/EitanWong/remote-dev-skillkit/internal/model"
	"github.com/EitanWong/remote-dev-skillkit/internal/operatorauth"
)

// Schema versions for all production managed host lifecycle types.
const (
	EnrollmentRequestSchemaVersion  = "rdev.managed-host-enrollment-request.v1"
	EnrollmentResponseSchemaVersion = "rdev.managed-host-enrollment-response.v1"
	TrustFetchRequestSchemaVersion  = "rdev.managed-host-trust-fetch-request.v1"
	TrustFetchResponseSchemaVersion = "rdev.managed-host-trust-fetch-response.v1"
	ReEnrollRequestSchemaVersion    = "rdev.managed-host-reenrollment-request.v1"
	ReEnrollResponseSchemaVersion   = "rdev.managed-host-reenrollment-response.v1"

	enrollmentRequestNonceSize = 32

	enrollmentRequestPayloadSchema = "rdev.managed-host-enrollment-request-payload.v1"
	reEnrollRequestPayloadSchema   = "rdev.managed-host-reenrollment-request-payload.v1"
)

// EnrollmentToken is a single-use token issued by an operator with the issuer
// role. It binds the allowed host mode and capabilities so the issuer endpoint
// can mint a certificate without an interactive ticket.
type EnrollmentToken struct {
	TokenID      string    `json:"token_id"`
	Mode         string    `json:"mode"`
	Capabilities []string  `json:"capabilities"`
	ExpiresAt    time.Time `json:"expires_at"`
}

// EnrollmentRequest is sent by a host to the production enrollment endpoint.
// The host presents its identity public key, a nonce for anti-replay, and the
// plaintext enrollment token that was pre-shared by an operator.
type EnrollmentRequest struct {
	SchemaVersion       string `json:"schema_version"`
	HostName            string `json:"host_name"`
	OS                  string `json:"os"`
	Arch                string `json:"arch"`
	IdentityKeyID       string `json:"identity_key_id"`
	IdentityPublicKey   string `json:"identity_public_key"`
	IdentityFingerprint string `json:"identity_fingerprint"`
	// EnrollmentToken is the plaintext issuer token from an operator with the
	// "issuer" role. It is consumed by the issuer endpoint and must never be
	// reused or stored after first use.
	EnrollmentToken string `json:"enrollment_token"`
	// Nonce is a random 32-byte value (base64url-encoded) generated by the
	// host. The issuer binds it to the certificate payload so that replayed
	// requests are rejected.
	Nonce string `json:"nonce"`
	// IdentityProof is an Ed25519 signature over the request payload (all
	// fields except IdentityProof itself). It proves the host holds the
	// private key corresponding to IdentityPublicKey.
	IdentityProof string `json:"identity_proof"`
}

// EnrollmentResponse is returned by the production enrollment endpoint.
type EnrollmentResponse struct {
	SchemaVersion string                          `json:"schema_version"`
	Certificate   model.HostEnrollmentCertificate `json:"certificate"`
	TrustBundle   model.SignedTrustBundle         `json:"trust_bundle"`
	GatewayURL    string                          `json:"gateway_url,omitempty"`
	IssuedAt      time.Time                       `json:"issued_at"`
}

// TrustFetchRequest is sent by a host to the gateway's trust-bundle endpoint.
// The host authenticates itself by signing the request with its identity key.
// The gateway verifies the certificate, checks the host is not revoked, and
// returns an update if a newer bundle is available.
type TrustFetchRequest struct {
	SchemaVersion   string    `json:"schema_version"`
	HostID          string    `json:"host_id"`
	CertFingerprint string    `json:"cert_fingerprint"`
	CurrentSequence int       `json:"current_sequence"`
	CurrentHash     string    `json:"current_hash"`
	RequestedAt     time.Time `json:"requested_at"`
	// RequestProof is an Ed25519 signature over the canonical JSON of all
	// other fields. It is verified against the host's enrolled identity key.
	RequestProof string `json:"request_proof"`
}

// TrustFetchResponse is returned by the gateway trust-bundle endpoint.
type TrustFetchResponse struct {
	SchemaVersion string                  `json:"schema_version"`
	Update        model.TrustBundleUpdate `json:"update"`
	RespondedAt   time.Time               `json:"responded_at"`
}

// ReEnrollmentRequest is sent by a host whose certificate is within the
// renewal window (or already expired). It presents the existing certificate
// as proof of prior enrollment and supplies a new identity public key.
type ReEnrollmentRequest struct {
	SchemaVersion          string                          `json:"schema_version"`
	HostID                 string                          `json:"host_id"`
	NewIdentityKeyID       string                          `json:"new_identity_key_id"`
	NewIdentityPublicKey   string                          `json:"new_identity_public_key"`
	NewIdentityFingerprint string                          `json:"new_identity_fingerprint"`
	PriorCertificate       model.HostEnrollmentCertificate `json:"prior_certificate"`
	Nonce                  string                          `json:"nonce"`
	// PriorCertProof is a signature over the re-enrollment request payload
	// made with the *old* (prior) identity private key. This proves the host
	// still holds the prior key and has not been replaced by an attacker.
	PriorCertProof string `json:"prior_cert_proof"`
}

// ReEnrollmentResponse is returned by the production re-enrollment endpoint.
type ReEnrollmentResponse struct {
	SchemaVersion string                          `json:"schema_version"`
	Certificate   model.HostEnrollmentCertificate `json:"certificate"`
	TrustBundle   model.SignedTrustBundle         `json:"trust_bundle"`
	IssuedAt      time.Time                       `json:"issued_at"`
}

// enrollmentRequestPayload is the canonical form signed by the host before
// sending an EnrollmentRequest. It omits the IdentityProof field.
type enrollmentRequestPayload struct {
	SchemaVersion       string `json:"schema_version"`
	HostName            string `json:"host_name"`
	OS                  string `json:"os"`
	Arch                string `json:"arch"`
	IdentityKeyID       string `json:"identity_key_id"`
	IdentityPublicKey   string `json:"identity_public_key"`
	IdentityFingerprint string `json:"identity_fingerprint"`
	EnrollmentToken     string `json:"enrollment_token"`
	Nonce               string `json:"nonce"`
}

// reEnrollRequestPayload is the canonical form signed by the host before
// sending a ReEnrollmentRequest. It omits the PriorCertProof field.
type reEnrollRequestPayload struct {
	SchemaVersion          string                          `json:"schema_version"`
	HostID                 string                          `json:"host_id"`
	NewIdentityKeyID       string                          `json:"new_identity_key_id"`
	NewIdentityPublicKey   string                          `json:"new_identity_public_key"`
	NewIdentityFingerprint string                          `json:"new_identity_fingerprint"`
	PriorCertificate       model.HostEnrollmentCertificate `json:"prior_certificate"`
	Nonce                  string                          `json:"nonce"`
}

// NewEnrollmentRequest builds a signed EnrollmentRequest for the host. The
// caller must supply a freshly generated identity key pair and an enrollment
// token obtained from an operator.
func NewEnrollmentRequest(
	hostName, os, arch, identityKeyID, enrollmentToken string,
	identityPublicKey ed25519.PublicKey,
	identityPrivateKey ed25519.PrivateKey,
) (EnrollmentRequest, error) {
	hostName = strings.TrimSpace(hostName)
	os = strings.TrimSpace(os)
	arch = strings.TrimSpace(arch)
	identityKeyID = strings.TrimSpace(identityKeyID)
	enrollmentToken = strings.TrimSpace(enrollmentToken)
	if hostName == "" || os == "" || arch == "" {
		return EnrollmentRequest{}, fmt.Errorf("host name, os, and arch are required")
	}
	if identityKeyID == "" {
		return EnrollmentRequest{}, fmt.Errorf("identity key id is required")
	}
	if len(identityPublicKey) != ed25519.PublicKeySize {
		return EnrollmentRequest{}, fmt.Errorf("invalid identity public key length %d", len(identityPublicKey))
	}
	if len(identityPrivateKey) != ed25519.PrivateKeySize {
		return EnrollmentRequest{}, fmt.Errorf("invalid identity private key length %d", len(identityPrivateKey))
	}
	if strings.TrimSpace(enrollmentToken) == "" {
		return EnrollmentRequest{}, fmt.Errorf("enrollment token is required")
	}
	pubKeyB64 := base64.RawURLEncoding.EncodeToString(identityPublicKey)
	fingerprint := model.NewTrustBundle(identityKeyID, identityPublicKey)
	fp, err := fingerprint.Fingerprint()
	if err != nil {
		return EnrollmentRequest{}, fmt.Errorf("compute identity fingerprint: %w", err)
	}
	nonce, err := generateNonce()
	if err != nil {
		return EnrollmentRequest{}, fmt.Errorf("generate nonce: %w", err)
	}
	req := EnrollmentRequest{
		SchemaVersion:       EnrollmentRequestSchemaVersion,
		HostName:            hostName,
		OS:                  os,
		Arch:                arch,
		IdentityKeyID:       identityKeyID,
		IdentityPublicKey:   pubKeyB64,
		IdentityFingerprint: fp,
		EnrollmentToken:     enrollmentToken,
		Nonce:               nonce,
	}
	payload, err := enrollmentRequestPayloadBytes(req)
	if err != nil {
		return EnrollmentRequest{}, fmt.Errorf("marshal enrollment request payload: %w", err)
	}
	req.IdentityProof = base64.RawURLEncoding.EncodeToString(ed25519.Sign(identityPrivateKey, payload))
	return req, nil
}

// ValidateEnrollmentRequest verifies an EnrollmentRequest at the issuer endpoint.
// It checks the schema, the identity proof, and authorizes the enrollment token
// against the supplied authorizer (which must have the issuer role).
func ValidateEnrollmentRequest(req EnrollmentRequest, auth *operatorauth.Authorizer, bearerHeader string) error {
	if req.SchemaVersion != EnrollmentRequestSchemaVersion {
		return fmt.Errorf("unsupported enrollment request schema %q", req.SchemaVersion)
	}
	if strings.TrimSpace(req.HostName) == "" || strings.TrimSpace(req.OS) == "" || strings.TrimSpace(req.Arch) == "" {
		return fmt.Errorf("enrollment request host name, os, and arch are required")
	}
	if strings.TrimSpace(req.IdentityKeyID) == "" || strings.TrimSpace(req.IdentityPublicKey) == "" || strings.TrimSpace(req.IdentityFingerprint) == "" {
		return fmt.Errorf("enrollment request identity fields are required")
	}
	if strings.TrimSpace(req.EnrollmentToken) == "" {
		return fmt.Errorf("enrollment token is required")
	}
	if strings.TrimSpace(req.Nonce) == "" {
		return fmt.Errorf("enrollment request nonce is required")
	}
	if strings.TrimSpace(req.IdentityProof) == "" {
		return fmt.Errorf("enrollment request identity proof is required")
	}
	publicKeyBytes, err := base64.RawURLEncoding.DecodeString(req.IdentityPublicKey)
	if err != nil {
		return fmt.Errorf("decode enrollment request identity public key: %w", err)
	}
	if len(publicKeyBytes) != ed25519.PublicKeySize {
		return fmt.Errorf("invalid enrollment request identity public key length %d", len(publicKeyBytes))
	}
	// Verify that the operator bearer token has the issuer role.
	if auth != nil && auth.Enabled() {
		if !auth.AuthorizeBearer(bearerHeader, operatorauth.RoleIssuer, operatorauth.RoleAdmin) {
			return fmt.Errorf("enrollment request requires issuer or admin authorization")
		}
	}
	// Verify the host's identity proof.
	payload, err := enrollmentRequestPayloadBytes(req)
	if err != nil {
		return fmt.Errorf("marshal enrollment request payload: %w", err)
	}
	sig, err := base64.RawURLEncoding.DecodeString(req.IdentityProof)
	if err != nil {
		return fmt.Errorf("decode enrollment request identity proof: %w", err)
	}
	if !ed25519.Verify(ed25519.PublicKey(publicKeyBytes), payload, sig) {
		return fmt.Errorf("enrollment request identity proof signature mismatch")
	}
	return nil
}

// NewTrustFetchRequest builds a signed TrustFetchRequest for the host. The
// host signs the request with its identity private key to prove its identity to
// the gateway without presenting a bearer token.
func NewTrustFetchRequest(
	hostID, certFingerprint, currentHash string,
	currentSequence int,
	identityPrivateKey ed25519.PrivateKey,
	now time.Time,
) (TrustFetchRequest, error) {
	hostID = strings.TrimSpace(hostID)
	certFingerprint = strings.TrimSpace(certFingerprint)
	if hostID == "" {
		return TrustFetchRequest{}, fmt.Errorf("host id is required")
	}
	if certFingerprint == "" {
		return TrustFetchRequest{}, fmt.Errorf("cert fingerprint is required")
	}
	if len(identityPrivateKey) != ed25519.PrivateKeySize {
		return TrustFetchRequest{}, fmt.Errorf("invalid identity private key length %d", len(identityPrivateKey))
	}
	req := TrustFetchRequest{
		SchemaVersion:   TrustFetchRequestSchemaVersion,
		HostID:          hostID,
		CertFingerprint: certFingerprint,
		CurrentSequence: currentSequence,
		CurrentHash:     currentHash,
		RequestedAt:     now.UTC(),
	}
	payload, err := trustFetchRequestPayloadBytes(req)
	if err != nil {
		return TrustFetchRequest{}, fmt.Errorf("marshal trust fetch request: %w", err)
	}
	req.RequestProof = base64.RawURLEncoding.EncodeToString(ed25519.Sign(identityPrivateKey, payload))
	return req, nil
}

// ValidateTrustFetchRequest verifies a TrustFetchRequest at the gateway. It
// checks the schema, looks up the host's enrolled identity public key by
// CertFingerprint, and verifies the request signature.
func ValidateTrustFetchRequest(req TrustFetchRequest, identityPublicKey ed25519.PublicKey, now time.Time) error {
	if req.SchemaVersion != TrustFetchRequestSchemaVersion {
		return fmt.Errorf("unsupported trust fetch request schema %q", req.SchemaVersion)
	}
	if strings.TrimSpace(req.HostID) == "" {
		return fmt.Errorf("trust fetch request host id is required")
	}
	if strings.TrimSpace(req.CertFingerprint) == "" {
		return fmt.Errorf("trust fetch request cert fingerprint is required")
	}
	if strings.TrimSpace(req.RequestProof) == "" {
		return fmt.Errorf("trust fetch request proof is required")
	}
	if req.RequestedAt.IsZero() {
		return fmt.Errorf("trust fetch request requested_at is required")
	}
	if len(identityPublicKey) != ed25519.PublicKeySize {
		return fmt.Errorf("invalid identity public key length %d", len(identityPublicKey))
	}
	payload, err := trustFetchRequestPayloadBytes(req)
	if err != nil {
		return fmt.Errorf("marshal trust fetch request: %w", err)
	}
	sig, err := base64.RawURLEncoding.DecodeString(req.RequestProof)
	if err != nil {
		return fmt.Errorf("decode trust fetch request proof: %w", err)
	}
	if !ed25519.Verify(identityPublicKey, payload, sig) {
		return fmt.Errorf("trust fetch request proof signature mismatch")
	}
	return nil
}

// NewReEnrollmentRequest builds a signed ReEnrollmentRequest for a host that is
// within the renewal window. The host signs with its OLD private key to prove
// continuity of identity. The new key pair is supplied for certificate rotation.
func NewReEnrollmentRequest(
	hostID string,
	newIdentityKeyID string,
	newIdentityPublicKey ed25519.PublicKey,
	priorCertificate model.HostEnrollmentCertificate,
	priorIdentityPrivateKey ed25519.PrivateKey,
) (ReEnrollmentRequest, error) {
	hostID = strings.TrimSpace(hostID)
	newIdentityKeyID = strings.TrimSpace(newIdentityKeyID)
	if hostID == "" {
		return ReEnrollmentRequest{}, fmt.Errorf("host id is required")
	}
	if newIdentityKeyID == "" {
		return ReEnrollmentRequest{}, fmt.Errorf("new identity key id is required")
	}
	if len(newIdentityPublicKey) != ed25519.PublicKeySize {
		return ReEnrollmentRequest{}, fmt.Errorf("invalid new identity public key length %d", len(newIdentityPublicKey))
	}
	if len(priorIdentityPrivateKey) != ed25519.PrivateKeySize {
		return ReEnrollmentRequest{}, fmt.Errorf("invalid prior identity private key length %d", len(priorIdentityPrivateKey))
	}
	pubKeyB64 := base64.RawURLEncoding.EncodeToString(newIdentityPublicKey)
	tb := model.NewTrustBundle(newIdentityKeyID, newIdentityPublicKey)
	fp, err := tb.Fingerprint()
	if err != nil {
		return ReEnrollmentRequest{}, fmt.Errorf("compute new identity fingerprint: %w", err)
	}
	nonce, err := generateNonce()
	if err != nil {
		return ReEnrollmentRequest{}, fmt.Errorf("generate nonce: %w", err)
	}
	req := ReEnrollmentRequest{
		SchemaVersion:          ReEnrollRequestSchemaVersion,
		HostID:                 hostID,
		NewIdentityKeyID:       newIdentityKeyID,
		NewIdentityPublicKey:   pubKeyB64,
		NewIdentityFingerprint: fp,
		PriorCertificate:       priorCertificate,
		Nonce:                  nonce,
	}
	payload, err := reEnrollRequestPayloadBytes(req)
	if err != nil {
		return ReEnrollmentRequest{}, fmt.Errorf("marshal re-enrollment request: %w", err)
	}
	req.PriorCertProof = base64.RawURLEncoding.EncodeToString(ed25519.Sign(priorIdentityPrivateKey, payload))
	return req, nil
}

// ValidateReEnrollmentRequest verifies a ReEnrollmentRequest at the issuer
// endpoint. It checks the schema, verifies the prior certificate against the
// enrollment root, and verifies the PriorCertProof signature.
func ValidateReEnrollmentRequest(req ReEnrollmentRequest, enrollmentRoot model.TrustBundle, priorIdentityPublicKey ed25519.PublicKey, now time.Time) error {
	if req.SchemaVersion != ReEnrollRequestSchemaVersion {
		return fmt.Errorf("unsupported re-enrollment request schema %q", req.SchemaVersion)
	}
	if strings.TrimSpace(req.HostID) == "" {
		return fmt.Errorf("re-enrollment request host id is required")
	}
	if strings.TrimSpace(req.NewIdentityKeyID) == "" || strings.TrimSpace(req.NewIdentityPublicKey) == "" || strings.TrimSpace(req.NewIdentityFingerprint) == "" {
		return fmt.Errorf("re-enrollment request new identity fields are required")
	}
	if strings.TrimSpace(req.Nonce) == "" {
		return fmt.Errorf("re-enrollment request nonce is required")
	}
	if strings.TrimSpace(req.PriorCertProof) == "" {
		return fmt.Errorf("re-enrollment request prior cert proof is required")
	}
	if len(priorIdentityPublicKey) != ed25519.PublicKeySize {
		return fmt.Errorf("invalid prior identity public key length %d", len(priorIdentityPublicKey))
	}
	// The prior certificate signature must be valid (allow expired so near-expiry renewals work).
	if err := model.VerifyHostEnrollmentCertificateSignature(req.PriorCertificate, enrollmentRoot, now); err != nil {
		return fmt.Errorf("re-enrollment prior certificate: %w", err)
	}
	// Verify continuity: the prior cert must cover the same host identity fingerprint.
	if req.PriorCertificate.SubjectIdentityFingerprint == "" {
		return fmt.Errorf("re-enrollment prior certificate subject identity fingerprint is required")
	}
	// Verify the PriorCertProof signature.
	payload, err := reEnrollRequestPayloadBytes(req)
	if err != nil {
		return fmt.Errorf("marshal re-enrollment request: %w", err)
	}
	sig, err := base64.RawURLEncoding.DecodeString(req.PriorCertProof)
	if err != nil {
		return fmt.Errorf("decode re-enrollment prior cert proof: %w", err)
	}
	if !ed25519.Verify(priorIdentityPublicKey, payload, sig) {
		return fmt.Errorf("re-enrollment prior cert proof signature mismatch")
	}
	return nil
}

// --- payload canonicalization helpers ---

func enrollmentRequestPayloadBytes(req EnrollmentRequest) ([]byte, error) {
	p := enrollmentRequestPayload{
		SchemaVersion:       enrollmentRequestPayloadSchema,
		HostName:            req.HostName,
		OS:                  req.OS,
		Arch:                req.Arch,
		IdentityKeyID:       req.IdentityKeyID,
		IdentityPublicKey:   req.IdentityPublicKey,
		IdentityFingerprint: req.IdentityFingerprint,
		EnrollmentToken:     req.EnrollmentToken,
		Nonce:               req.Nonce,
	}
	return json.Marshal(p)
}

func trustFetchRequestPayloadBytes(req TrustFetchRequest) ([]byte, error) {
	// We sign all fields except RequestProof by marshalling without it.
	p := struct {
		SchemaVersion   string    `json:"schema_version"`
		HostID          string    `json:"host_id"`
		CertFingerprint string    `json:"cert_fingerprint"`
		CurrentSequence int       `json:"current_sequence"`
		CurrentHash     string    `json:"current_hash"`
		RequestedAt     time.Time `json:"requested_at"`
	}{
		SchemaVersion:   req.SchemaVersion,
		HostID:          req.HostID,
		CertFingerprint: req.CertFingerprint,
		CurrentSequence: req.CurrentSequence,
		CurrentHash:     req.CurrentHash,
		RequestedAt:     req.RequestedAt.UTC(),
	}
	return json.Marshal(p)
}

func reEnrollRequestPayloadBytes(req ReEnrollmentRequest) ([]byte, error) {
	p := reEnrollRequestPayload{
		SchemaVersion:          reEnrollRequestPayloadSchema,
		HostID:                 req.HostID,
		NewIdentityKeyID:       req.NewIdentityKeyID,
		NewIdentityPublicKey:   req.NewIdentityPublicKey,
		NewIdentityFingerprint: req.NewIdentityFingerprint,
		PriorCertificate:       req.PriorCertificate,
		Nonce:                  req.Nonce,
	}
	return json.Marshal(p)
}

func generateNonce() (string, error) {
	b := make([]byte, enrollmentRequestNonceSize)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}
